---
title: "Ethnic Population Patterns in Wayne County"
author: "Jincheng Yao"
subtitle: EAS 648, Lab 1
output:
  html_document:
    highlight: tango
    theme: cerulean
  pdf_document: default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
#code chunk to put in default settings, like whether other code chunks run/show messages
knitr::opts_chunk$set(echo = TRUE, 
                      messages = FALSE)

# Set so that long lines in R will be wrapped:
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), tidy=TRUE)
#note may need to install and load package "formatR" for this to run. 

options (width = 80)

```



```{r 1, include=FALSE}
library(ggplot2)
library(tidycensus)
library(tidyverse)
library(tmap)
library(tmaptools)
library(dplyr)        
library(sf)      
library(RColorBrewer) 
library(classInt)     
library(tidyverse)      
library(cartography) 
library(SpatialPosition)
library(maptiles) 
library(terra)
library(potential)
library(ggpubr)

# general setting
census_api_key("2495886b30a9eed86c09bc346d16b8febef89ddc")


black_pal    <- colorRampPalette(c("#F2E5FF", "#4B0082"))  
asian_pal    <- colorRampPalette(c("#E3F2FD", "#0D47A1"))  
hisp_pal     <- colorRampPalette(c("#FFF3E0", "#E65100"))  
white_pal    <- colorRampPalette(c("#F5F5F5", "#616161"))  



#color for plots
point_colors <- c(
  White    = "#616161",
  Black    = "#4B0082",
  Asian    = "#0D47A1",
  Hispanic = "#E65100"
)

fill_colors <- c(
  White    = "#F5F5F5",
  Black    = "#F2E5FF",
  Asian    = "#E3F2FD",
  Hispanic = "#FFF3E0"
)

# data
racevars <- c(
  White      = "P005003",
  Black      = "P005004",
  Asian      = "P005006",
  Hispanic   = "P004003",
  HouseUnits = "H001001",
  Rent       = "H004004"
)

Wayne <- tidycensus::get_decennial(
  geography   = "tract",
  variables   = racevars,
  state       = "MI",
  county      = "Wayne",
  year        = 2010,
  sumfile     = "sf1",      
  geometry    = TRUE,
  summary_var = "P001001"   # total population
)

Wayne <- Wayne %>%
  tidyr::pivot_wider(
    names_from  = variable,   
    values_from = value,
    values_fill = 0           # fill missing group counts with 0
  ) 

names(Wayne)[names(Wayne) == "summary_value"] <- "Pop2010"


# project Wayne County data to NAD83 / UTM zone 17N
Wayne <- sf::st_transform(Wayne, 26917)


```

```{r 2, echo = TRUE}
# index about population
Wayne <- Wayne %>%
  mutate(
    #counting the share
    WhiteShare    = White / Pop2010 * 1000,
    BlackShare    = Black / Pop2010 * 1000,
    AsianShare    = Asian / Pop2010 * 1000,
    HispanicShare = Hispanic / Pop2010 * 1000,
    
    #counting the proportion
    WhiteProportion    = White / sum(White) * 1000,
    BlackProportion    = Black / sum(Black) * 1000,
    AsianProportion    = Asian / sum(Asian) * 1000,
    HispanicProportion = Hispanic / sum(Hispanic) * 1000,
    
    #counting Location Quotient
    White_LQ    = (White    / Pop2010) / (sum(White)    / sum(Pop2010)),
    Black_LQ    = (Black    / Pop2010) / (sum(Black)    / sum(Pop2010)),
    Asian_LQ    = (Asian    / Pop2010) / (sum(Asian)    / sum(Pop2010)),
    Hispanic_LQ = (Hispanic / Pop2010) / (sum(Hispanic) / sum(Pop2010))
  )
```



```{r 3, echo = TRUE}
#breaks for proportion
brks_Pop <- c(0, 0.1, 0.5, 1, 2, 5)

# map for ethnic proportion
par(mfrow = c(2, 2), mar = c(0,0.5,0.5,0),oma = c(0,0,1.5,0))

# white
cartography::choroLayer(
  x = Wayne,
  var = "WhiteProportion",
  #method = "quantile",
  nclass = 5,
  col = white_pal(5),
  breaks = brks_Pop,
  border = "grey70",
  
  legend.pos = "bottomright",
  legend.title.txt = "",
  legend.values.rnd = 2)

mtext("White\nProportion(‰)",
      side = 3,
      line = -9.5,
      adj = 0.95,
      font = 2,
      cex = 0.9,
      col = "#616161")


# black
cartography::choroLayer(
  x = Wayne,
  var = "BlackProportion",
  #method = "quantile",
  nclass = 5,
  col = black_pal(5),
  breaks = brks_Pop,
  border = "grey70",
  
  legend.pos = "bottomright",
  legend.title.txt = "",
  legend.values.rnd = 2)
mtext("Black\nProportion(‰)",
      side = 3,
      line = -9.5,
      adj = 0.95,
      font = 2,
      cex = 0.9,
      col = "#4B0082")

# asian
cartography::choroLayer(
  x = Wayne,
  var = "AsianProportion",
  #method = "quantile",
  nclass = 5,
  col = asian_pal(5),
  breaks = brks_Pop,
  border = "grey70",
  
  legend.pos = "bottomright",
  legend.title.txt = "",
  legend.values.rnd = 2)
mtext("Asian\nProportion(‰)",
      side = 3,
      line = -9.5,
      adj = 0.95,
      font = 2,
      cex = 0.9,
      col = "#0D47A1")

# hispanic
cartography::choroLayer(
  x = Wayne,
  var = "HispanicProportion",
  #method = "quantile",
  nclass = 5,
  col = hisp_pal(5),
  breaks = brks_Pop,
  border = "grey70",
  
  legend.pos = "bottomright",
  legend.title.txt = "",
  legend.values.rnd = 2
)

mtext("Hispanic\nProportion(‰)",
      side = 3,
      line = -9.5,
      adj = 0.95,
      font = 2,
      cex = 0.9,
      col = "#E65100")


par(mfrow=c(1,1))

# global legend
cartography::layoutLayer(
  title = "",
  author = "Jincheng Yao",
  sources = "US Census 2010",
  north = FALSE,
  scale = FALSE,
  frame = FALSE
)

bb <- sf::st_bbox(Wayne)
x1 <- bb["xmax"] + 0.04 * (bb["xmax"] - bb["xmin"])
x2 <- bb["xmax"] - 0.01 * (bb["xmax"] - bb["xmin"])
y1 <- bb["ymax"] - 0.12 * (bb["ymax"] - bb["ymin"])
y2 <- bb["ymax"] - 0.20 * (bb["ymax"] - bb["ymin"])
cartography::north(pos = c(x1, y1))
cartography::barscale(pos = c(x2, y2),  unit = "km")


mtext("Ethnic Group Population Share in Wayne County (2010)",
      side = 3, 
      outer = TRUE, 
      line = -0.2, 
      cex = 1.6, 
      font = 2)


```




```{r 4, echo = TRUE}
#breaks for LQ
max_LQ <- max(Wayne$White_LQ, Wayne$Black_LQ, Wayne$Asian_LQ, Wayne$Hispanic_LQ, na.rm = TRUE)
brks_LQ <- c(0, 0.5, 1, 2, 20)

# map for ethnic Location Quotient (LQ)
par(mfrow = c(2, 2), mar = c(0,0.5,0.5,0),oma = c(0,0,1.5,0))

# white
cartography::choroLayer(
  x = Wayne,
  var = "White_LQ",
  #method = "quantile",
  nclass = 5,
  col = white_pal(5),
  breaks = brks_LQ,
  border = "grey70",
  
  legend.pos = "bottomright",
  legend.title.txt = "",
  legend.values.rnd = 2)

mtext("White LQ",
      side = 3,
      line = -9.5,
      adj = 0.95,
      font = 2,
      cex = 0.9,
      col = "#616161")


# black
cartography::choroLayer(
  x = Wayne,
  var = "Black_LQ",
  #method = "quantile",
  nclass = 5,
  col = black_pal(5),
  breaks = brks_LQ,
  border = "grey70",
  
  legend.pos = "bottomright",
  legend.title.txt = "",
  legend.values.rnd = 2)
mtext("Black LQ",
      side = 3,
      line = -9.5,
      adj = 0.95,
      font = 2,
      cex = 0.9,
      col = "#4B0082")

# asian
cartography::choroLayer(
  x = Wayne,
  var = "Asian_LQ",
  #method = "quantile",
  nclass = 5,
  col = asian_pal(5),
  breaks = brks_LQ,
  border = "grey70",
  
  legend.pos = "bottomright",
  legend.title.txt = "",
  legend.values.rnd = 2)
mtext("Asian LQ",
      side = 3,
      line = -9.5,
      adj = 0.95,
      font = 2,
      cex = 0.9,
      col = "#0D47A1")

# hispanic
cartography::choroLayer(
  x = Wayne,
  var = "Hispanic_LQ",
  #method = "quantile",
  nclass = 5,
  col = hisp_pal(5),
  breaks = brks_LQ,
  border = "grey70",
  legend.pos = "bottomright",
  
  legend.title.txt = "",
  legend.values.rnd = 2
)

mtext("Hispanic LQ",
      side = 3,
      line = -9.5,
      adj = 0.95,
      font = 2,
      cex = 0.9,
      col = "#E65100")


par(mfrow=c(1,1))

# global legend
cartography::layoutLayer(
  title = "",
  author = "Jincheng Yao",
  sources = "US Census 2010",
  north = FALSE,
  scale = FALSE,
  frame = FALSE
)

bb <- sf::st_bbox(Wayne)
x1 <- bb["xmax"] + 0.04 * (bb["xmax"] - bb["xmin"])
x2 <- bb["xmax"] - 0.01 * (bb["xmax"] - bb["xmin"])
y1 <- bb["ymax"] - 0.15 * (bb["ymax"] - bb["ymin"])
y2 <- bb["ymax"] - 0.23 * (bb["ymax"] - bb["ymin"])
cartography::north(pos = c(x1, y1))
cartography::barscale(pos = c(x2, y2),  unit = "km")


mtext("Ethnic Group Population Share in Wayne County (2010)",
      side = 3, 
      outer = TRUE, 
      line = -0.2, 
      cex = 1.6, 
      font = 2)


```


```{r 5, echo = TRUE}
# data prepare for bar chart
Wayne_df <- Wayne %>%
  as.data.frame() %>%
  select(NAME,
         WhiteProportion, BlackProportion, AsianProportion, HispanicProportion,
         White_LQ, Black_LQ, Asian_LQ, Hispanic_LQ)

# proportion
prop_long <- Wayne_df %>%
  select(NAME, ends_with("Proportion")) %>%
  pivot_longer(
    cols = -NAME,
    names_to = "Group",
    values_to = "Value"
  ) %>%
  mutate(
    Group = sub("Proportion", "", Group),
    Metric = "Proportion"
  )

# LQ
lq_long <- Wayne_df %>%
  select(NAME, ends_with("LQ")) %>%
  pivot_longer(
    cols = -NAME,
    names_to = "Group",
    values_to = "Value"
  ) %>%
  mutate(
    Group = sub("_LQ", "", Group),
    Metric = "LQ"
  )

Wayne_long <- bind_rows(prop_long, lq_long)

Wayne_long$Metric <- factor(
  Wayne_long$Metric,
  levels = c("Proportion", "LQ")
)

```

```{r 6, echo = TRUE,warning=FALSE}
# boxplot
ggplot(Wayne_long, aes(x = Group, y = Value)) +

  geom_boxplot(
    aes(fill = Group, color = Group),
    size = 0.9,
    outlier.shape = NA
  ) +
  scale_fill_manual(values = fill_colors) +
  scale_color_manual(values = point_colors) +
  facet_wrap(~Metric, ncol = 1) +
  ylim(0, 4) +
  geom_hline(data = subset(Wayne_long, Metric == "LQ"),
             aes(yintercept = 1),
             linetype = "dashed",
             color = "grey25") +
  labs(
    title = "Ethnic Group Proportion vs Location Quotient",
    subtitle = "Wayne County, Michigan",
    x = "Ethnic Group",
    y = "Value"
  ) +
  theme_minimal(base_size = 14) +
  
  #setting of background
  theme(
  legend.position = "none",
  strip.text = element_text(face = "bold", size = 14),
  axis.title.x = element_text(face = "bold"),
  axis.title.y = element_text(face = "bold"),

  
  strip.background = element_rect(fill = "white", color = NA),
  panel.background = element_blank(),
  plot.background = element_blank(),
  panel.grid = element_blank(),
  axis.line = element_line(color = "black", size = 0.6),
  axis.ticks = element_line(color = "black", size = 0.5),
  plot.title = element_text(face ="bold", hjust = 0.5),
  plot.subtitle = element_text(hjust = 0.5)
)





```



Proportion captures local majority/minority structures, while LQ captures the spatial importance of each tract for a racial group. Both are necessary to properly understand racial segregation patterns.